#coding:utf-8
API_ERROR_SIGN_CODE = 1
API_ERROR_SIGN_TXT = 'API签名错误'

API_ERROR_SIGN = {
    'code': API_ERROR_SIGN_CODE,
    'txt':API_ERROR_SIGN_TXT
}

API_ERROR_LOGIN_CODE = 2
API_ERROR_LOGIN_TXT = '用户登录的SESSION错误'
API_ERROR_LOGIN = {
    'code': API_ERROR_LOGIN_CODE,
    'txt': API_ERROR_LOGIN_TXT
}



