#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Zsite
CID_USER = 1

CID_ZSITE = CID_USER,

# Pic
CID_ICO = 31
CID_ICO96 = 32
CID_PO_PIC = 35

CID_PIC = CID_ICO, CID_ICO96, CID_PO_PIC

# Po
CID_WORD = 61
CID_NOTE = 62
CID_QUESTION = 63
#CID_ANSWER = 64

CID_PO = CID_WORD, CID_NOTE, CID_QUESTION#, CID_ANSWER

# Notice
CID_INVITE_REGISTER = 91
CID_NOTICE_REGISTER = 92
CID_NOTICE_WALL = 93
CID_NOTICE_WALL_REPLY = 94
CID_INVITE_QUESTION = 95
CID_NOTICE_QUESTION = 96
CID_MAIL_MONTH = 97
CID_MAIL_YEAR = 98

# User Verify
CID_VERIFY_MAIL = 121
CID_VERIFY_PASSWORD = 122
CID_VERIFY_MONEY = 123

# Trade Order
CID_TRADE_CHARDE = 151
CID_TRADE_WITHDRAW = 152
CID_TRADE_DEAL = 153
CID_TRADE_REWARD = 154

# Pay Type
CID_PAY_ALIPAY = 181
CID_PAY_DONATE = 182

# Buzz
CID_BUZZ_SYS = 211
CID_BUZZ_SHOW = 212
CID_BUZZ_FOLLOW = 213
CID_BUZZ_WALL = 214
CID_BUZZ_WALL_REPLY = 215
CID_BUZZ_PO_REPLY = 216
