#coding:utf-8

from model.cid import CID_BUZZ_SYS, CID_BUZZ_FOLLOW, CID_BUZZ_WALL, CID_BUZZ_WALL_REPLY, CID_BUZZ_PO_REPLY, CID_BUZZ_ANSWER, CID_BUZZ_EVENT_JOIN,\
 CID_BUZZ_EVENT_FEEDBACK_JOINER, CID_BUZZ_EVENT_FEEDBACK_OWNER, CID_USER, CID_BUZZ_SITE_NEW , CID_BUZZ_SITE_FAV, CID_BUZZ_WORD_AT



CID_BUZZ_BLOCK_AT = 1
CID_BUZZ_BLOCK_8GUA = 2
CID_BUZZ_BLOCK_REPLY = 3

BUZZ_CID2LIST = {
    CID_BUZZ_BLOCK_AT     : (
        CID_BUZZ_WORD_AT,
    ),
    CID_BUZZ_BLOCK_8GUA : (
        CID_BUZZ_FOLLOW,
        CID_BUZZ_SITE_NEW,
        CID_BUZZ_SITE_FAV,
        CID_BUZZ_EVENT_JOIN,
    ),
    CID_BUZZ_BLOCK_REPLY  : (
        CID_BUZZ_PO_REPLY,
        CID_BUZZ_ANSWER,
        CID_BUZZ_EVENT_FEEDBACK_JOINER,
        CID_BUZZ_EVENT_FEEDBACK_OWNER,
        CID_BUZZ_WALL
    ),
}
