#coding:utf-8

OAUTH_GOOGLE = 1
OAUTH_DOUBAN = 2
OAUTH_SINA = 3
OAUTH_TWITTER = 4
OAUTH_WWW163 = 5
OAUTH_BUZZ = 6
OAUTH_SOHU = 7
OAUTH_QQ = 8
OAUTH_RENREN = 9
OAUTH_LINKEDIN = 10

OAUTH2NAME = (
    (OAUTH_DOUBAN, '豆瓣'),
    (OAUTH_SINA, '新浪微博'),
    (OAUTH_QQ, '腾讯微博'),
    (OAUTH_BUZZ, 'Google+'),
    (OAUTH_TWITTER, 'Twitter'),
    (OAUTH_LINKEDIN, 'LinkedIn'),

)
