#!/usr/bin/env python
# -*- coding: utf-8 -*-

STATE_RM = 3
STATE_APPLY = 5
STATE_SECRET = 7
STATE_ACTIVE = 10

STATE_PO_ZSITE_REVIEW_THEN_SHOW = 15
STATE_PO_ZSITE_SHOW_THEN_REVIEW = 20
STATE_PO_ZSITE_REVIEWED = 25

STATE_BUZZ_RM = 0
STATE_BUZZ_ACTIVE = 1
