s="""feed://scrumalliance.org/rss
http://1eef0.pn.ipc.la/?feed=rss2
http://2years.net/feed/
http://517onlyone.blog.163.com/rss/
http://61.160.200.212:8080/wordpress/feed/
http://9noon.blogbus.com/index.rdf
http://abjkl.blogbus.com/index.rdf
http://adamghost.com/feed/
http://adrin.cn/?feed=rss2
http://ajax.lu/feed/
http://alphachoi.com/feed
http://angela.ucdchina.com/?feed=rss2
http://ansonyi.com/feed/
http://api.fanfou.com/statuses/user_timeline/kaopulove.rss
http://api.fanfou.com/statuses/user_timeline/leesoliloquy.rss
http://api.fanfou.com/statuses/user_timeline/lindatou.rss
http://api.fanfou.com/statuses/user_timeline/longbill.rss
http://api.fanfou.com/statuses/user_timeline/micy.rss
http://api.fanfou.com/statuses/user_timeline/niphanin.rss
http://api.fanfou.com/statuses/user_timeline/yukirock.rss
http://artdeng.blog.163.com/rss/
http://ash1990.blogbus.com/index.rdf
http://avenger.name/feed/
http://backend.deviantart.com/rss.xml?q=by%3Aluceiola&type=journal&formatted=1
http://bbs.jieshi.com/forum.php?mod=rss&auth=0
http://bbs.jieshi.com/forum.php?mod=rss&auth=0
http://biflife.blog.163.com/rss/
http://blog.0478inc.com/?feed=rss2
http://blog.163.com/microcat_1980/rss/
http://blog.94smart.com/feed
http://blog.akajia.com/?feed=rss2
http://blog.bliwy.info/rss.xml
http://blog.bmn.me/feed
http://blog.bordf.com/feed/
http://blog.bukn.info/?feed=rss2
http://blog.cainanyang.com/feed/
http://blog.csdn.net/bincker/rss/list
http://blog.csdn.net/carol2000/rss/list
http://blog.csdn.net/lxbhxwl/rss/list
http://blog.csdn.net/soasme/rss/list
http://blog.csdn.net/Solstice/rss/list
http://blog.csdn.net/turingbook/rss/list
http://blog.csdn.net/vividonly/rss/list
http://blog.csdn.net/xushiweizh/rss/list
http://blog.csdn.net/yang_net/rss/list
http://blog.dofilab.com/feed/
http://blog.donews.com/jiji262/feed/
http://blog.dreamcog.com/?feed=rss2
http://blog.hippoh.org/feed
http://blog.hiwind.info/blog/feed/
http://blog.huihoo.com/?feed=rss2
http://blog.hysia.com/feed
http://blog.igevin.info/feed
http://blog.libing.org/feed
http://blog.lrain.net/?feed=rss2
http://blog.offidea.com/?feed=rss2
http://blog.olsoso.com/feed/
http://blog.onbaqu.com/?feed=rss2
http://blog.opvps.com/feed/
http://blog.pluswu.com/feed
http://blog.sina.com.cn/rss/1053175593.xml
http://blog.sina.com.cn/rss/1134411104.xml
http://blog.sina.com.cn/rss/1163690892.xml
http://blog.sina.com.cn/rss/1170814221.xml
http://blog.sina.com.cn/rss/1171915250.xml
http://blog.sina.com.cn/rss/1194882373.xml
http://blog.sina.com.cn/rss/1217962323.xml
http://blog.sina.com.cn/rss/1227316034.xml
http://blog.sina.com.cn/rss/1231057423.xml
http://blog.sina.com.cn/rss/1231423357.xml
http://blog.sina.com.cn/rss/1233236715.xml
http://blog.sina.com.cn/rss/1243429431.xml
http://blog.sina.com.cn/rss/1259096105.xml
http://blog.sina.com.cn/rss/1266391280.xml
http://blog.sina.com.cn/rss/1270787132.xml
http://blog.sina.com.cn/rss/1283637627.xml
http://blog.sina.com.cn/rss/1283678450.xml
http://blog.sina.com.cn/rss/1287339305.xml
http://blog.sina.com.cn/rss/1320097102.xml
http://blog.sina.com.cn/rss/1408154202.xml
http://blog.sina.com.cn/rss/1411211934.xml
http://blog.sina.com.cn/rss/1414733623.xml
http://blog.sina.com.cn/rss/1415990537.xml
http://blog.sina.com.cn/rss/1418987422.xml
http://blog.sina.com.cn/rss/1441070767.xml
http://blog.sina.com.cn/rss/1465265113.xml
http://blog.sina.com.cn/rss/1508230037.xml
http://blog.sina.com.cn/rss/1526039490.xml
http://blog.sina.com.cn/rss/1560849092.xml
http://blog.sina.com.cn/rss/1572362721.xml
http://blog.sina.com.cn/rss/1574018043.xml
http://blog.sina.com.cn/rss/1579900615.xml
http://blog.sina.com.cn/rss/1582070753.xml
http://blog.sina.com.cn/rss/1593119885.xml
http://blog.sina.com.cn/rss/1618218610.xml
http://blog.sina.com.cn/rss/1621376722.xml
http://blog.sina.com.cn/rss/1640079900.xml
http://blog.sina.com.cn/rss/1651615587.xml
http://blog.sina.com.cn/rss/1654165383.xml
http://blog.sina.com.cn/rss/1662838245.xml
http://blog.sina.com.cn/rss/1676418231.xml
http://blog.sina.com.cn/rss/1687117684.xml
http://blog.sina.com.cn/rss/1720122753.xml
http://blog.sina.com.cn/rss/1729274557.xml
http://blog.sina.com.cn/rss/1739606415.xml
http://blog.sina.com.cn/rss/1770225005.xml
http://blog.sina.com.cn/rss/1781291421.xml
http://blog.sina.com.cn/rss/1792545595.xml
http://blog.sina.com.cn/rss/1795447317.xml
http://blog.sina.com.cn/rss/1805093694.xml
http://blog.sina.com.cn/rss/1805154091.xml
http://blog.sina.com.cn/rss/1819859555.xml
http://blog.sina.com.cn/rss/1824394853.xml
http://blog.sina.com.cn/rss/48282992.xml
http://blog.thephper.com/feed.php
http://blog.timger.info/feed
http://blog.vista.tw/feed
http://blog.yufeng.info/feed
http://blog.zhangjun.net/?feed=rss2
http://blog.zhuli.name/feed
http://boostguy.blogspot.com/feeds/posts/default
http://bss.appspot.com/feed
http://caoruijie.com/index.php/feed
http://centiejian.blog.163.com/rss/
http://chenqj.org/blog/?feed=rss2
http://chenzongzhi.info/?feed=rss2
http://cshongyin.blog.163.com/rss/
http://cugfeng.sinaapp.com/feed/
http://daichuanqing.com/index.php/feed
http://daoguangying.blog.163.com/rss/
http://decemfirst.tk/feed/
http://dengjin.com/feed
http://digu.com/statuses/rss/huihui_lain.rss
http://docute.com/feed/
http://doc.zhoubo.name/?feed=rss2
http://dongzhenhua.com/?feed=rss2
http://doublethinklog.com/rss
http://dribbble.com/S.Shek/shots.rss
http://drunkencherry.blogcn.com/feed
http://eatsalt.blog.163.com/rss/
http://edinburghpunk.wordpress.com/feed/
http://eggfan.org/feed
http://ethos.im/feed
http://eventstructure.com/feed-rss.php?url=es
http://fangkc.z.infzm.com/feed/
http://fcjblog.com/feed
http://feed.ecvip.org/
http://feed.feedsky.com/5imanbu_all
http://feed.feedsky.com/allendog
http://feed.feedsky.com/arsun
http://feed.feedsky.com/hoterran
http://feed.feedsky.com/jiangmiao
http://feed.feedsky.com/laiwei
http://feed.feedsky.com/liuxinzhi
http://feed.feedsky.com/moorekang
http://feed.feedsky.com/namiheike
http://feed.feedsky.com/ProgrammingNoteCN
http://feed.feedsky.com/qiushid
http://feed.feedsky.com/sunwei922
http://feed.feedsky.com/WebFuns
http://feed.feedsky.com/zlovezl_blog
http://feed.keeptry.com/
http://feed.marchbox.com/
http://feed.mtime.com/comment.rss
http://feed.paradisefeng.com/
http://feed.piscdong.com/
http://feed.ppcode.com/
http://feed.raychou.com/
http://feed.rexsong.com/
http://feeds.feedburner.com/bighead
http://feeds.feedburner.com/dulao5
http://feeds.feedburner.com/lzyy
http://feeds.feedburner.com/maple
http://feeds.feedburner.com/sonny87
http://feeds.feedburner.com/tarwonmm
http://feeds.feedburner.com/v2ex/latest
http://feeds.feedburner.com/zhufengme
http://feeds.feedsky.com/5key
http://feeds.feedsky.com/csdn.net/kingofark
http://feeds.kenengba.com/kenengbarss
http://feedsky.blogbus.com/77sunny_blogbus_com
http://feedsky.blogbus.com/cometrace_blogbus_com
http://feedsky.blogbus.com/firenzemc_blogbus_com
http://feedsky.blogbus.com/lanpicn_blogbus_com
http://feedsky.blogbus.com/luoyu712_blogbus_com
http://feedsky.blogbus.com/lyx538_blogbus_com
http://feedsky.blogbus.com/ottoo_blogbus_com
http://feedsky.blogbus.com/tuxiaoming_blogbus_com
http://feedsky.blogbus.com/tzhou_blogbus_com
http://feedsky.blogbus.com/wukaijj1314_blogbus_com
http://feedsky.blogbus.com/yuanyun_blogbus_com
http://feedsky.blogbus.com/zjsbird_blogbus_com
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=20867092
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=22553616
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=342473230
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=363371755
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=421750020
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=438620893
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=5350174
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=578788963
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=942181047
http://feeds.qzone.qq.com/cgi-bin/cgi_rss_out?uin=992079
http://feed.uitony.com/
http://feed.w757.com/
http://feed.yinzi.org/
http://feiran.sinaapp.com/?feed=rss2
http://flyvenus.net/wordpress/?feed=rss2
http://freefis.appspot.com/feed
http://fwso.cn/feed/
http://gaoyonghua.blog.hexun.com/rss2.aspx
http://gashero.javaeye.com/rss
http://gecanhui.com/feed/
http://gezhi.org/comments/feed
http://gezhi.org/feed
http://github.com/Fleurer.atom
http://gongli135hi.blog.163.com/rss/
http://googleyixia.com/feed
http://gossipcoder.com/?feed=rss2
http://gravitysworm.tumblr.com/rss
http://guanmin.wordpress.com/feed/
http://haizimen.org/index.php/feed/
http://helloqidi.iteye.com/rss
http://henter.me/feed
http://hi.baidu.com/13524552030/rss
http://hi.baidu.com/bngoogle/rss
http://hi.baidu.com/%C0%CF%B8%CA/rss
http://hi.baidu.com/%C0%EE%D1%D7%BB%D6/rss
http://hi.baidu.com/%C4%F4%CA%F7%C6%BD/rss
http://hi.baidu.com/%C7%C73%C9%D9/rss
http://hi.baidu.com/cenghouhui/rss
http://hi.baidu.com/%D3%CE%CF%B7%B2%A1%BA%A2%D7%D3/rss
http://hi.baidu.com/hiraby/rss
http://hi.baidu.com/loxtfire/rss
http://hi.baidu.com/me_zmoon/rss
http://hi.baidu.com/mimimo/rss
http://hi.baidu.com/qiyiguo919/rss
http://hi.baidu.com/strive/rss
http://hi.baidu.com/totrit/rss
http://hi.baidu.com/wsxiaogao/rss
http://hi.baidu.com/xixingcong/rss
http://hi.baidu.com/xiyunliang/rss
http://hi.baidu.com/xlikecheng/rss
http://hi.baidu.com/zbccfan/rss
http://hi.baidu.com/zheng918/rss
http://hi.baidu.com/zhenuu/rss
http://hiengo.com/feed
http://houlei123000.blog.163.com/rss/
http://huangxiaolong.com/x2/feed.asp
http://huluzasui.diandian.com/rss
http://hyry.dip.jp/rss.xml
http://ialog.com/feed/
http://iarjun.com/feed
http://ibear99.com/feed
http://icepeach.net/blog/?feed=atom
http://icewent.com/feed
http://iduo8.diandian.com/rss
http://ilab.iteye.com/rss
http://imjennifer.com/feed/
http://iworm.smugmug.com/hack/feed.mg?Type=nickname&Data=iworm&format=atom10
http://izero.diandian.com/rss
http://jamzoblogs.appspot.com/index.xml
http://janeva.me/feed/
http://jasonwei.com/?feed=rss2
http://jinhao.javaeye.com/rss
http://jiy.hu/feed
http://jolestar.com/feed
http://junyuedongfang.com/feed
http://juxiaoxi.com/feed
http://kainy.cn/feed/
http://kebinwang.wordpress.com/feed/
http://keenmisty.com/index.php/feed
http://ketech.me/feed/
http://kingbase.org/blog/feed/
http://lamtin.cc/?feed=rss2
http://landsonzhao.wordpress.com/feed/
http://lanty1984.blogbus.com/index.rdf
http://leehomes.blogbus.com/index.rdf
http://leeking001.com/?feed=rss2
http://leicado.com/index.php?x=rss
http://leiicon.net/feed/
http://leiyue.wordpress.com/feed/
http://leogray.net/
http://lgone.com/feed
http://liaohui1688.blog.163.com/rss/
http://lichgo.com/feed/
http://limengxue124.blogcn.com/
http://linpython.sinaapp.com/?feed=rss2
http://lintb.kuandao.com/feed
http://liomao.iteye.com/rss
http://lisahello.blog.163.com/rss/
http://lisam.4.blog.163.com/rss/
http://littlemiss1988.com/feed
http://liuchuang.t.sohu.com/rss/40962
http://liulixiang.info/feed/
http://lvguoning.com/feed/
http://lvwei.me/feed
http://lvzei.yo1yo5.com/rss.php
http://ly50247.appspot.com/feed
http://mdchina.org/?feed=rss2
http://mgoblogapp.appspot.com/feed
http://migangel.diandian.com/rss
http://mindlee.net/feed/
http://miniironman.com/feed/atom/
http://mojay.org/feed/
http://mrchou.com/feed
http://mzai.net/index.php/feed/
http://naxiaoxin.com/?feed=rss2
http://never2ever.com/typecho/index.php/feed/
http://nius.me/feed/
http://ocool.us/feed/
http://ofshellohicy.info/feed
http://osmn00.com/rss.xml
http://osnryo.tumblr.com/rss
http://oyangz.blogcn.com/feed
http://pcuseman.com/?feed=rss2
http://pfstudio.diandian.com/rss
http://picplz.com/user/alvintshia/picfeed.rss/
http://pkb.cn/index.php?feed=rss
http://qingbo.net/blog/rss/
http://richiay.com/?feed=rss2
http://riku.me/feed
http://rlog.cn/?feed=rss2
http://robinzhu.diandian.com/rss
http://rockliu.com/feed/
http://rss.tudou.com/userID/310262
http://rss.xaoxua.com/
https://github.com/anrs.atom
https://github.com/withrock.atom
http://shiyj.heroku.com/index.xml
http://shuaike.org/feed
http://shuoyangdesign.com/feed/
https://ibeca.me/feed/
http://simplelifestyle.diandian.com/rss
http://skyxqc.wordpress.com/feed/
http://snswe.com/feed
http://sociallearnlab.org/xiuli/?feed=rss2
http://somepig2009.blogbus.com/index.rdf
http://spud.in/feed
http://sunchen.kuandao.com/feed
http://sunliwen.com/feed/
http://sunxiunan.com/?feed=rss2
http://sysbioinfo.com/?feed=rss2
http://tangjiachen.com/?feed=rss2
http://tech2ipo.com/feed/
http://tech.crandom.com/feed
http://techsingular.net/?feed=rss2
http://todwang.blogspot.com/feeds/posts/default
http://tonyyet.com/feed
http://troycheng.blogcn.com/feed
http://ttmgo.com/?feed=rss2
http://tubie.me/feed/
http://typecho.org/feed/
http://uepstudio.com/blog/?feed=rss2
http://uicom.net/blog/?feed=rss2
http://uxat.me/feed/
http://waityournews.blog.163.com/rss/
http://walkmyway.tk/feed/
http://wangcong.org/blog/?feed=rss2
http://wangshuo2046.com/?feed=rss2
http://wangwanqing.com/feed
http://wangx.com/feed/
http://wangyueblog.com/feed/
http://wchenx.blogbus.com/index.rdf
http://webto.diandian.com/rss
http://whisper.eyesay.org/feed/
http://whoyang.blog.163.com/rss/
http://whx.me/feed
http://winnielin.com/feed/
http://www.1000hamlets.com/feed
http://www.1234567i.org/rss.php?action=index
http://www.1986914.com/?feed=rss2
http://www.199it.com/feed
http://www.36kr.com/feed
http://www.4418.net/?feed=rss2
http://www.4glife.cn/index.php/feed
http://www.5kkm.com/feed
http://www.6ceng.com/?feed=rss2
http://www.798library.com/home/feed/rss/?format=feed
http://www.7tank.com/blog/feed/
http://www.91python.com/feed
http://www.9liangban.com/feed.php?ename=beijing
http://www.abublog.info/?feed=rss2
http://www.aifeitou.com/feed/
http://www.allsaying.com/index.php?format=feed&type=rss
http://www.anyonedy.com/?feed=rss2
http://www.bapond.com/feed
http://www.bigheadx.com/?feed=rss2
http://www.bitbao.net/blog/?feed=rss2
http://www.blogjava.net/scud/rss.aspx
http://www.bobhou.cn/?feed=rss2
http://www.boyso.net.cn/rss.php?action=index
http://www.budoued.com/?feed=rss2
http://www.cad.zju.edu.cn/home/zhx/rss-articles/
http://www.catisf.com/feed/
http://www.cbdtuan.com/feed.php?ename=beijing
http://www.chaishubang.com/?feed=rss2
http://www.chenguangblog.com/feed
http://www.chenxianjiang.com/feed/atom
http://www.chenxiaosheng.com/feed
http://www.cheungfei.com/?feed=atom
http://www.choudou.com/feed
http://www.cnblogs.com/Alexander-Lee/rss
http://www.cnblogs.com/flyingzl/rss
http://www.cnblogs.com/hackergodness/rss
http://www.cnblogs.com/houfeng/rss
http://www.cnblogs.com/Jerry-Chou/rss
http://www.cnblogs.com/Jesse-Luo/rss
http://www.cnblogs.com/kqingchao/rss
http://www.cnblogs.com/kym/rss
http://www.cnblogs.com/liubiqu/rss
http://www.cnblogs.com/lopezycj/rss
http://www.cnblogs.com/miloyip/rss
http://www.cnblogs.com/qq78292959/rss
http://www.cnblogs.com/seanlv/rss
http://www.cnblogs.com/xiaogangqq123/rss
http://www.cnblogs.com/yanng/rss
http://www.cnblogs.com/yemingchong/rss
http://www.cnblogs.com/zhaoguo435/rss
http://www.cngadget.cn/feed
http://www.cnspirit.com/?feed=rss2
http://www.cnxct.com/feed/
http://www.codeo4.cn/feed
http://www.colincao.net/?feed=rss2
http://www.crispedu.org/blog/feed.php
http://www.crossyou.cn/feed/atom
http://www.csfqw.com/API/Rss.aspx
http://www.css88.com/feed
http://www.cxxcn.com/feed
http://www.dbanotes.net/atom.xml
http://www.dedream.com/research/index.rdf
http://www.dezai.cn/blog/feed.asp
http://www.digu.com/statuses/rss/fishking1979.rss
http://www.dingdianer.com/?feed=rss2
http://www.disound.com/blog/?feed=rss2
http://www.douban.com/feed/group/bj/discussion
http://www.douban.com/feed/group/jee_linux/discussion
http://www.douban.com/feed/group/su27/discussion
http://www.douban.com/feed/group/wenzhi/discussion
http://www.douban.com/feed/group/yaoqing/discussion
http://www.douban.com/feed/people/2251385/notes
http://www.douban.com/feed/people/2251385/reviews
http://www.douban.com/feed/people/3166953/notes
http://www.douban.com/feed/people/3166953/notes
http://www.douban.com/feed/people/3166953/reviews
http://www.douban.com/feed/people/3166953/reviews
http://www.douban.com/feed/people/35821668/notes
http://www.douban.com/feed/people/35821668/reviews
http://www.douban.com/feed/people/3790438/notes
http://www.douban.com/feed/people/3790438/reviews
http://www.douban.com/feed/people/3899025/notes
http://www.douban.com/feed/people/3899025/reviews
http://www.douban.com/feed/people/42309178/notes
http://www.douban.com/feed/people/42309178/reviews
http://www.douban.com/feed/people/bovzou/notes
http://www.douban.com/feed/people/bovzou/reviews
http://www.douban.com/feed/people/bsmagic/notes
http://www.douban.com/feed/people/bsmagic/reviews
http://www.douban.com/feed/people/funkyheresy/notes
http://www.douban.com/feed/people/funkyheresy/reviews
http://www.douban.com/feed/people/gigix/notes
http://www.douban.com/feed/people/gigix/reviews
http://www.douban.com/feed/people/lidaobing/notes
http://www.douban.com/feed/people/lidaobing/reviews
http://www.douban.com/feed/people/magicsilence/notes
http://www.douban.com/feed/people/magicsilence/reviews
http://www.douban.com/feed/people/sayayan/notes
http://www.douban.com/feed/people/sayayan/reviews
http://www.douban.com/feed/people/sharplhl/notes
http://www.douban.com/feed/people/sharplhl/reviews
http://www.douban.com/feed/people/xiaqqaix/notes
http://www.douban.com/feed/people/xiaqqaix/reviews
http://www.douban.com/feed/people/zhenzhendewo/notes
http://www.douban.com/feed/people/zhenzhendewo/reviews
http://www.douban.com/photos/album/26357141/cooliris
http://www.douhua.im/feed/
http://www.dunsh.org/feed/
http://www.duobiduo.com/feed
http://www.duqq.com/feed/
http://www.ecnotes.com/feed/
http://www.elmerzhang.com/feed/
http://www.eovon.com/feed
http://www.erdaren.com/feed
http://www.fallhunter.com/feed
http://www.feeloc.cn/feed
http://www.feime.net/feed/
http://www.fm021.com/feed/
http://www.fmyworld.net/?feed=rss2
http://www.freetstar.com/index.php/feed
http://www.fuzhijie.me/?feed=rss2
http://www.fxydesigner.com/feed/
http://www.gafish.net/feed
http://www.gaoph.com/?feed=rss2
http://www.girlcoding.com/feed/
http://www.goddie.cn/goddie/rss.xml
http://www.hanxu.cc/feed/
http://www.haofei.org/?feed=rss2
http://www.helishi.net/feed/
http://www.hidecloud.com/blog/feed
http://www.hoowolf.net/feed/
http://www.hozin.com/rss/rss.xml
http://www.huntist.cn/rss.xml
http://www.iamued.com/feed
http://www.idsoo.com/rss.xml
http://www.iirr.info/blog/?feed=rss2
http://www.ikent.me/blog/feed
http://www.inhy.net/forum.php?mod=rss&auth=0
http://www.iptu.net/index.php/feed
http://www.ipujia.com/feed
http://www.itfeel.com/feed
http://www.itjiao.cn/feed.asp
http://www.iwillwen.com/feed
http://www.jackacey.com/feed/
http://www.jayzhou.com.cn/feed/
http://www.jiacheo.org/feed
http://www.jimli.cn/?feed=rss2
http://www.jingweb.com/feed/
http://www.jinzhao.info/feed
http://www.joshes.cn/rss.xml
http://www.jqmobile.org/rss.php?auth=0
http://www.justidle.net/feed
http://www.kevinsan.com/feed
http://www.kingson.org/?feed=rss2
http://www.klstudio.com/rss.xml
http://www.k-zone.cn/zblog/rss.xml
http://www.larro.cn/feed
http://www.leeon.me/feed
http://www.letresbon.com/?feed=rss2
http://www.lifecrunch.biz/feed
http://www.likuiseo.cn/index.php/feed
http://www.linkahomes.com/feed/
http://www.linuxschool.net/rss.xml
http://www.linxiaoyao.com/?feed=rss2
http://www.linxun.info/?feed=rss2
http://www.lishiliang.info/?feed=rss2
http://www.liuhanyu.com/feed/
http://www.liulantao.com/portal/feed/
http://www.liuwenzhi.com/forum.php?mod=rss&auth=0
http://www.livebrand.cn/blog/rss.xml
http://www.lofir.com/feed.xml
http://www.logolomo.com/feed
http://www.lsproc.com/blog/feed/
http://www.luoyundeng.com/?feed=rss2
http://www.mazhiyuan.net/feed
http://www.mepine.com/?feed=rss2
http://www.mycimt.cn/rss.php?rssid=429
http://www.newbeelab.com/?feed=rss2
http://www.nooidea.com/weblog/feed
http://www.orczhou.com/index.php/feed/
http://www.paitoubing.cn/blog/feed
http://www.pamedia.com.cn/feed/
http://www.pihai.me/feed
http://www.plidezus.net/?feed=rss2
http://www.pmroad.net/?feed=rss2
http://www.pocadvertising.com/%E9%A6%96%E9%A1%B5/feed/
http://www.pub4.com/rss.php
http://www.qibuy.com/feed.xml
http://www.rfstory.com/rss/
http://www.rockdai.com/?feed=rss2
http://www.seeisee.com/index.php/feed
http://www.seoservices.cn/feed
http://www.shangcui.net/feed
http://www.shiranyu.com/feed/
http://www.shizhouming.com/feed/
http://www.showeb20.com/?feed=rss2
http://www.simujj.com/?feed=rss2
http://www.sswowo.com/feed.asp
http://www.sunbo.name/feed
http://www.supercucu.info/?feed=rss2
http://www.thecodeway.com/blog/?feed=rss2
http://www.tobycn.org/feed
http://www.uxfan.com/feed/
http://www.uxsong.com/?feed=rss2
http://www.veryued.org/feed/
http://www.visionpan.com/?feed=rss2
http://www.wangmao.me/feed
http://www.wangyuelou.org/?feed=rss2
http://www.webchina110.cn/?feed=rss2
http://www.wenfeixiang.com/feed/
http://www.wh199.com/feed/
http://www.wheatv.com/feed
http://www.whodesign.me/feed/
http://www.wybai.net/?feed=rss2
http://www.wzxue.com/feed/
http://www.x2it.net/rss.php
http://www.xiami.com/collect/feed
http://www.xiangwangfeng.com/feed/
http://www.xiaodouban.com/feed/
http://www.xiaoker.com/feed/
http://www.xiaoyangsheng.com/feed/
http://www.xiaozhili.com/feed/
http://www.xi-ju.com/p/feed
http://www.xmued.com/?feed=rss2
http://www.xxniao.org/index.php/feed/
http://www.xyzzw.net/rss.php
http://www.yafeishi.net/blog/feed/
http://www.yankun.org/feed/
http://www.yaozhifeng.net/feed/
http://www.yoocle.cn/feed
http://www.youtaidu.net/feed
http://www.yudaijun.com/?feed=rss2
http://www.yuexiaodao.com/rss.xml
http://www.zensh.com/feed/
http://www.zhangyiqun.net/feed
http://www.zhkzyth.com/wordpress/?feed=rss2
http://www.zhuhongtao.com/index.php/feed
http://xiaoqiang.me/?feed=rss2
http://xipin.diandian.com/rss
http://xlvector.net/blog/?feed=rss2
http://xning.me/feed
http://xoops.org.cn/backend.php
http://yangyue1974.blog.sohu.com/rss
http://yaword.com/?feed=rss2
http://yier0220.blog.163.com/rss/
http://yinwm.com/feed/
http://zhaolei.info/rss
http://zhaqiang.com/feed/
http://zhengkun.info/feed/
http://zhongwenbin001.blog.sohu.com/rss
http://zhouzq1975.wordpress.com/feed/
http://zhubin.cc/feed
http://zhu.gd/feed/
http://zhupengfei.com/feed/
http://zqyin.wordpress.com/feed/
http://zwkufo.blog.163.com/rss/
http://zxyun.blog.163.com/rss/"""

s = s.split()
print s

import _env
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from zkit.google.greader import Reader
reader = Reader('42qu.com','')

for i in s:
    reader.subscribe(i)
    print i
    sys.stdout.flush()



